[CMSP-42] Fixed issue with empty/zero value for posts_per_page
pantheon-systems/solr-power pull request #599
Opened 2023-07-25 19:24 UTC by pwtyler

Set posts_per_page to default to 1 if not set.

Replaces #567
Fixes #566.

2023-07-25 21:48 UTC, jazzsequence requested changes
use `posts_per_page` value from the database as a default rather than hard-coding to 1.

2023-07-25 21:48 UTC, jazzsequence commented on includes/class-solrpower-wp-query.php
> +		$posts_per_page = ( ! $query->get( 'posts_per_page' ) ) ? 1 : $query->get( 'posts_per_page' );
I think this should be set to a more intelligent default if it's not set.

```suggestion
		$posts_per_page = get_option( 'posts_per_page' ) ?? 10;
		$posts_per_page = ( ! $query->get( 'posts_per_page' ) ) ? $posts_per_page : $query->get( 'posts_per_page' );
```

2023-07-26 04:53 UTC, pwtyler commented on includes/class-solrpower-wp-query.php
> +		$posts_per_page = ( ! $query->get( 'posts_per_page' ) ) ? 1 : $query->get( 'posts_per_page' );
Not sure if two nested defaults is worse than two ternaries but I didn't like ^ lol
```suggestion
		$posts_per_page = $query->get('posts_per_page', get_option('posts_per_page', 10));
```

2023-07-26 15:19 UTC, jazzsequence approved these changes

2023-07-26 15:19 UTC, jazzsequence commented
:shipit:

2023-07-26 16:41 UTC, merged